// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const sqlcCreateFilesItem = `-- name: SqlcCreateFilesItem :one
INSERT INTO files (user_id, parent_id, attachment_id, created_at, type, name, original_name)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type SqlcCreateFilesItemParams struct {
	UserID       int64
	ParentID     pgtype.Int8
	AttachmentID string
	CreatedAt    pgtype.Timestamp
	Type         VpBackendFilesTypeEnum
	Name         string
	OriginalName string
}

func (q *Queries) SqlcCreateFilesItem(ctx context.Context, arg SqlcCreateFilesItemParams) (int64, error) {
	row := q.db.QueryRow(ctx, sqlcCreateFilesItem,
		arg.UserID,
		arg.ParentID,
		arg.AttachmentID,
		arg.CreatedAt,
		arg.Type,
		arg.Name,
		arg.OriginalName,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
