name: Golang-App-Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-GoApplication:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-Repository
        uses: actions/checkout@v4

      - name: Setup-Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true
      - run: go version

      - name: Verify dependencies
        run: go mod verify

      - name: Install-Golang-Dependencies
        run: go mod download

      - name: Build-Golang-App
        run: GOOS=linux go build -o bin/rd_hub  -v ./cmd/rd_hub/

      - name: Display-Build-Golang-App
        run: ls -R bin/

      - name: Run go vet
        run: go vet ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./...

      - name: Run-Unit-Test-Golang-App
        run: go test -race -vet=off ./...
