name: Golang-App-Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-GoApplication:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-Repository
        uses: actions/checkout@v4

      - name: Setup-Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true
      - run: go version

      - name: Verify dependencies
        run: go mod verify

      - name: Install-Golang-Dependencies
        run: go mod download

      - name: Build-Golang-App
        run: GOOS=linux go build -o build/rd_hub  -v ./cmd/rd_hub/

      - name: Display-Build-Golang-App
        run: ls -R build/

      - name: Display-Build-Golang-App
        run: ls -la .

      - name: Run go vet
        run: go vet ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./...

      - name: Run-Unit-Test-Golang-App
        run: go test -race -vet=off ./...

#      - name: SCP to server ( Binary )
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          port: ${{ secrets.SSH_PORT }}
#          source: .
#          target: ${{ secrets.PROJECT_LOCATION }};

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.PROJECT_LOCATION }}
            git pull origin main
            go build -o bin/rdhub ./cmd/rd_hub/

      - name: Restart service
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo ${{ secrets.PROJECT_LOCATION }};
            systemctl --user restart rdhub;

#      - name: Run command on remote server
#        uses: D3rHase/ssh-command-action@v0.3.1
#        with:
#          host: ${{secrets.SSH_HOST}}
#          user: ${{secrets.SSH_USER}}
#          private_key: ${{secrets.SSH_PRIVATE_KEY}}
#          command: |
#            cd ${{ secrets.PROJECT_FOLDER }};
#            git checkout main;
#            git pull;
#            systemctl --user restart rd-hub;
